# numpy

 - one of the core packages for numerical computing in python
 - many packages are built on top of numpy
 - `numpy` has been optimized for processing: faster due to memory access

# Variables
we can think of variables as a name we assign to a particular object in python. for example:

In [7]:
#assign a small array to a variable a
import numpy as np
a = np.array([ [1,1,22], [3,5,8] ])

when we run the cell, we store the variable and its value. We can see the variables value im two ways:

In [8]:
a

array([[ 1,  1, 22],
       [ 3,  5,  8]])

In [9]:
print(a)

[[ 1  1 22]
 [ 3  5  8]]


## naming variables

in the class we are going to use `snake_case` for naming variables.

# variables and objects

**object**: often encountered in python documnetation and tutorials.

object is a bundle of properties and actions about something specific

Example:
- object: data frame
- properties: number of rows, names of colums, data creaated
- actions: selecting a row, adding a column

A variable is a name we give a specific object and the same object can be reference by different variable

Example:
- The Sun (the actual star at the center of solar system) = object
- sol = spanish word for sun = variable
- soleil = French for Sun = another variable

in practice: we will use object and variable interchangeably

# Types

Each object in python has a type.

type = what kind of object it is

we can also call the type of the object, the **class** of the object.

We can see the type/class of an object by using the `type` function:


In [10]:
print(a)
type(a)

[[ 1  1 22]
 [ 3  5  8]]


numpy.ndarray

the `numpy.ndarray` is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing: 

In [11]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [12]:
# how would you access yhr value 5 in the array?

In [15]:
print(a[1,1])

5


# Function

`print` was our example of a python function! :)

a function:
- take in a set of **arguments**, separated by commas, and 
- use those arguments to produce some **output**

argument = parameter : you might argument most often in the documentation
we can ask information about a function by executing `?` followed by the function name

In [16]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in parenthesis
- then a short description of what the function does
- finally, a list of the arguments and a brief explanation of each of them.

different types of arguments inside the parenthesis. Roughly speaking, there are two types of argumentss:
- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional arguments++: arguments that are prefilled with a default value by the function, but we can overrride them, optional arguments appear inside the parenthesis () in the form

`optional argument = default_value`


In [17]:
print('changing the default end argument of the print function', end = ':)')

changing the default end argument of the print function:)

In [18]:
print('changing the default end argument of the print function')

changing the default end argument of the print function
