# numpy

 - one of the core packages for numerical computing in python
 - many packages are built on top of numpy
 - `numpy` has been optimized for processing: faster due to memory access

# Variables
we can think of variables as a name we assign to a particular object in python. for example:

In [7]:
#assign a small array to a variable a
import numpy as np
a = np.array([ [1,1,22], [3,5,8] ])

when we run the cell, we store the variable and its value. We can see the variables value im two ways:

In [8]:
a

array([[ 1,  1, 22],
       [ 3,  5,  8]])

In [9]:
print(a)

[[ 1  1 22]
 [ 3  5  8]]


## naming variables

in the class we are going to use `snake_case` for naming variables.

# variables and objects

**object**: often encountered in python documnetation and tutorials.

object is a bundle of properties and actions about something specific

Example:
- object: data frame
- properties: number of rows, names of colums, data creaated
- actions: selecting a row, adding a column

A variable is a name we give a specific object and the same object can be reference by different variable

Example:
- The Sun (the actual star at the center of solar system) = object
- sol = spanish word for sun = variable
- soleil = French for Sun = another variable

in practice: we will use object and variable interchangeably

# Types

Each object in python has a type.

type = what kind of object it is

we can also call the type of the object, the **class** of the object.

We can see the type/class of an object by using the `type` function:


In [10]:
print(a)
type(a)

[[ 1  1 22]
 [ 3  5  8]]


numpy.ndarray

the `numpy.ndarray` is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing: 

In [11]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [12]:
# how would you access yhr value 5 in the array?

In [15]:
print(a[1,1])

5


# Function

`print` was our example of a python function! :)

a function:
- take in a set of **arguments**, separated by commas, and 
- use those arguments to produce some **output**

argument = parameter : you might argument most often in the documentation
we can ask information about a function by executing `?` followed by the function name

In [16]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in parenthesis
- then a short description of what the function does
- finally, a list of the arguments and a brief explanation of each of them.

different types of arguments inside the parenthesis. Roughly speaking, there are two types of argumentss:
- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional arguments++: arguments that are prefilled with a default value by the function, but we can overrride them, optional arguments appear inside the parenthesis () in the form

`optional argument = default_value`


In [17]:
print('changing the default end argument of the print function', end = ':)')

changing the default end argument of the print function:)

In [18]:
print('changing the default end argument of the print function')

changing the default end argument of the print function


# Attributes and methods

an object in Python has attributes and methods

- **attributes**: a property of an object, a piece of information about it
- **methods**: a proceduce associated with an object, an action where the main ingredient is the object itself.\

access a variable's attributes and methods by adding a period`.` at the end of the variable's name

`variable.variable_method()` or
`variable.variable_attribute`

examples:

methods and attributes of NumPy arrays:


In [3]:
import numpy as np

In [4]:
# define a 3x3 array

var = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
# shape : attribute telling us the number of elements in each dimention of the array

In [5]:
type(var.shape)

tuple

In [6]:
# ndim is an attribute holding the number of array dimensions
var.ndim

2

In [7]:
type(var.ndim)

int

notice attributes can have many different data types

In [ ]:
# example of methods
#return the min value of the array

In [9]:
var.min()

1

In [13]:
type(var.min)

builtin_function_or_method

# R and Python

r:
- doesnt use methods within an object
- functions in R are extrinsic to (outside) the objects they are acting on

example: recreate the min value of an array

In R, there would be two separate items: the variable `var` and a *separate* functyion `min` that gets `var` as a parameter

``` this is R code
var = array(c(1,4,7,2,5,8,3,6,9), dim = c(3,3)
min(var)
```

using the pipe operator in R's tidyverse is closer to the `.` in Python:

```
var = array(c(1,4,7,2,5,8,3,6,9), dim = c(3,3)
var >%> min()
```
What is happening?

the pipe `>%>` is passing `var` to the `min()` as its first argument. this is essentially what the `.` in python:

```
var = np.array( [ [1,2,3], [4,5,6], [7,8,9] } )

```
